# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61b23faf09abce24dd49d81dbb612f55628168d9a43b9b0761256414eaf6b02df163621f13f7f0f76f3889e37949ace4e29c6b644cfab7089374433aa620ddaa

test:
  secret_key_base: 259338cf2235117a1cac3789cc2ffcdffa1de017d76777838d710583599445a0ba83bb4173be119063598adba98af22e518c6e50c7e84f0ce9ebd35ae2751755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
