# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Article.destroy_all
Comment.destroy_all

article1 = Article.create!(title: "Great Post 2015", text: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas. Dramatically maintain clicks-and-mortar solutions without functional solutions. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.")
article2 = Article.create!(title: "Article is really Good", text: "So the Tankadere kept steadily on her northward track. The night was really terrible; it would be a miracle if the craft did not founder.  Twice it could have been all over with her if the crew had not been constantly on the watch.  Aouda was exhausted, but did not utter a complaint.  More than once Mr. Fogg rushed to protect her from the violence of the waves. Day reappeared.  The tempest still raged with undiminished fury; but the wind now returned to the south-east.  It was a favourable change, and the Tankadere again bounded forward on this mountainous sea, though the waves crossed each other, and imparted shocks and counter-shocks which would have crushed a craft less solidly built.  From time to time the coast was visible through the broken mist, but no vessel was in sight.  The Tankadere was alone upon the sea. There were some signs of a calm at noon, and these became more distinct as the sun descended toward the horizon.  The tempest had been as brief as terrific.  The passengers, thoroughly exhausted, could now eat a little, and take some repose. The night was comparatively quiet.  Some of the sails were again hoisted, and the speed of the boat was very good.  The next morning at dawn they espied the coast, and John Bunsby was able to assert that they were not one hundred miles from Shanghai.  A hundred miles, and only one day to traverse them!  That very evening Mr. Fogg was due at Shanghai, if he did not wish to miss the steamer to Yokohama.  Had there been no storm, during which several hours were lost, they would be at this moment within thirty miles of their destination. The wind grew decidedly calmer, and happily the sea fell with it.  All sails were now hoisted, and at noon the Tankadere was within forty-five miles of Shanghai.  There remained yet six hours in which to accomplish that distance.  All on board feared that it could")
article3 = Article.create!(title: "The Princess of Mars" , text: "'With extras?' asked the Mock Turtle a little anxiously. 'Yes,' said Alice, 'we learned French and music.' 'And washing?' said the Mock Turtle. 'Certainly not!' said Alice indignantly. 'Ah! then yours wasn't a really good school,' said the Mock Turtle in  a tone of great relief. 'Now at OURS they had at the end of the bill,  French, music, AND extra.' 'You couldn't have wanted it much,' said Alice; 'living at the bottom of  the sea.' 'I couldn't afford to learn it.' said the Mock Turtle with a sigh. 'I  only took the regular course.' 'What was that?' inquired Alice. 'Reeling and Writhing, of course, to begin with,' the Mock Turtle")
article4 = Article.create!(title: "Can you tell me where we used to be?", text: "'You'll see me there,' said the Cat, and vanished. Alice was not much surprised at this, she was getting so used to queer  things happening. While she was looking at the place where it had been,  it suddenly appeared again. 'By-the-bye, what became of the baby?' said the Cat. 'I'd nearly  forgotten to ask.' 'It turned into a pig,' Alice quietly said, just as if it had come back  in a natural way. 'I thought it would,' said the Cat, and vanished again. Alice waited a little, half expecting to see it again, but it did not  appear")
article5 = Article.create!(title: "I don't think like that anymore", text: "So, setting about it as methodically as men might smoke out a wasps' nest, the Martians spread this strange stifling vapour over the Londonward country.  The horns of the crescent slowly moved apart, until at last they formed a line from Hanwell to Coombe and Malden. All night through their destructive tubes advanced.  Never once, after the Martian at St. George's Hill was brought down, did they give the artillery the ghost of a chance against them.  Wherever there was a possibility of guns being laid for them unseen, a fresh canister of the black")
article6 = Article.create!(title: "But mom said I could", text: "Consider all this; and then turn to this green, gentle, and most docile earth; consider them both, the sea and the land; and do you not find a strange analogy to something in yourself? For as this appalling ocean surrounds the verdant land, so in the soul of man there lies one insular Tahiti, full of peace and joy, but encompassed by all the horrors of the half known life. God keep thee! Push not off from that isle, thou canst never return! Slowly wading through the meadows of brit, the Pequod still held on her way north-eastward towards the island of Java; a gentle air impelling her keel, so that in the surrounding serenity her three tall tapering masts mildly waved to that languid breeze, as three mild palms on a plain. And still, at wide intervals in the silvery night, the lonely, alluring jet would be seen. But one transparent blue morning, when a stillness almost preternatural")

article1.comments.create!(commenter: "Bruce Wayne", body: "Consider all this; and then turn to this green, gentle, and" )
article1.comments.create!(commenter: "Martha Washington", body: "The news of the massacre probably reached Chobham, Woking, and Ottershaw about the" )
article1.comments.create!(commenter: "Your Mom", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )


article2.comments.create!(commenter: "Alice Wonderland", body: "In front was a quiet sunny landscape, a wheat field ahead on either side of the road, and the Maybury Inn with its swinging sign.  I saw" )
article2.comments.create!(commenter: "Martha Stewart", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )
article2.comments.create!(commenter: "Hank Green", body: "Consider all this; and then turn to this green, gentle, and" )

article3.comments.create!(commenter: "John Green", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )
article3.comments.create!(commenter: "Bob Ross", body: "In front was a quiet sunny landscape, a wheat field ahead on either side of the road, and the Maybury Inn with its swinging sign.  I saw" )
article3.comments.create!(commenter: "Cat Person", body: "Consider all this; and then turn to this green, gentle, and" )

article4.comments.create!(commenter: "Dog Person", body: "In front was a quiet sunny landscape, a wheat field ahead on either side of the road, and the Maybury Inn with its swinging sign.  I saw" )
article4.comments.create!(commenter: "Michelle Obama", body: "Consider all this; and then turn to this green, gentle, and" )
article4.comments.create!(commenter: "Beyonce", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )

article5.comments.create!(commenter: "Easter Bunny", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )
article5.comments.create!(commenter: "Santa", body: "Consider all this; and then turn to this green, gentle, and" )
article5.comments.create!(commenter: "Al Picino", body: "In front was a quiet sunny landscape, a wheat field ahead on either side of the road, and the Maybury Inn with its swinging sign.  I saw" )

article6.comments.create!(commenter: "Aunt Sally", body: "In front was a quiet sunny landscape, a wheat field ahead on either side of the road, and the Maybury Inn with its swinging sign.  I saw" )
article6.comments.create!(commenter: "Dumbledor", body: "But again he leaned over towards the people, and bowing his head lowly, with an aspect of the" )
article6.comments.create!(commenter: "Ron Weasley", body: "Consider all this; and then turn to this green, gentle, and" )
